/* Phal AutoGenerated .ino file 
*  Created 15-05-2018
*/

#include "Lightbulb.h" 
#include "TemperatureSensor.h" 
bool satan = true;
bool god = false;
bool alive = true;
bool dead = false;
void setup(){ 
pinMode(1, OUTPUT);
pinMode(2, OUTPUT);
pinMode(5, OUTPUT);
pinMode(2, INPUT);
dead = true;
delay((32)*1000);
if(true == false){
dead = true;

}
else if(true){
dead = false;
}
else{
alive = false;
}} 

void loop(){ 
if(true == false && false == false){
if(true == false && 21 > 30){
satan = false;
god = alive;

}
else if(god == alive){
satan = dead;
}
else if(satan == alive){
satan = dead;
}
else{
alive = false;
}
}
} 

float waitup (float num){
float num1;
float num2;
num += 45;
num1 += 45;

}
float waitufp (float num, float five){
float num1;
float num2;
num += 45;
num1 += 45;
if(num1 == 4){
num2 = 3;

}
else if(num < 3){
num = 4;
}
else if(five >= 3){
five = 2;
}
else{
num2 = num1;
}delay((2.5)*1000);
return 15;
}
