/* Phal AutoGenerated .ino file 
*  Created 11-05-2018
*/

#include "Lightbulb.h" 
#include "TemperatureSensor.h" 
bool satan = true;
bool god = false;
bool alive = true;
bool dead = false;
void setup(){ 
} 

void loop(){ 
} 

