import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

import enums.*;

public class CodeGeneration extends Visitor{

	private PrintWriter writer;
	private List<Type> ComponentIncludesMap;
	
	public CodeGeneration(List<Type> CIM) {
		ComponentIncludesMap = CIM;
		try {
			writer = new PrintWriter(new FileWriter( MainClass.inputFileName + ".ino", false));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	

	private void printHeader() {
		writer.print("/* Phal AutoGenerated .ino file \n"
				     + "*  Created " + new SimpleDateFormat("dd-MM-yyyy").format(new Date()) 
				     + "\n*/\n\n"
					 );
	}
	private void printCmpIncludes(String using) {
		writer.print("#include \"" + using +".h\" \n"
				     );
	}
	
	@Override
	public void visit(ProgramNode node) {
		printHeader();
		
		writer.close();
	}
}
 