import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;

import enums.*;

public class CodeGeneration extends Visitor{

	private PrintWriter writer;
	private HashMap<Type, Boolean> ComponentIncludesMap;
	
	public CodeGeneration(HashMap<Type, Boolean> CIM) {
		ComponentIncludesMap = CIM;
		try {
			writer = new PrintWriter(new FileWriter( "../phal/PhalLangEx4/" + MainClass.inputFileName + ".ino", false));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	

	private void printHeader() {
		writer.print("/* Phal AutoGenerated .ino file \n"
				     + "*  Created " + new SimpleDateFormat("dd-MM-yyyy").format(new Date()) 
				     + "\n*/\n\n"
					 );
	}
	private void printCmpIncludes() {
		writer.print("#include \"Lightbulb.h\" \n"
				     + "#include \"Motor.h\" \n"
				     + "#include \"TemperatureSensor.h\"\n"
				     );
	}
	
	@Override
	public void visit(ProgramNode node) {
		printHeader();
		
		for(SetupCntNode dcl : node.setupNode.setupCntNodes) {
			writer.print(dcl.dclNode.idNode.type + " " + dcl.dclNode.idNode.id + " = " + " ;\n");
		}
		
		// visit includes
		
		visit(node.setupNode);
		visit(node.repeatNode);
		
		writer.close();
	}
	
	@Override
	public void visit(SetupNode node) {
		writer.print("void setup(){ \n");
		// visit setup
		writer.print("} \n\n");
	}
	
	@Override
	public void visit(RepeatNode node) {
		writer.print("void loop(){ \n");
		// visit nodes
		writer.print("} \n\n");
	}
}
 