/* Phal AutoGenerated .ino file 
*  Created 20-05-2018
*/

#include "Lightbulb.h" 
#include "PhalGroup.h"
#include "PhalList.h"
Lightbulb *lb1;
Lightbulb *lb2;
Lightbulb *lb3;
Lightbulb *lb4;
Lightbulb *lb5;
Lightbulb *lb6;
PhalGroup *lights = new PhalGroup();
void setup(){ 
lb1 = new Lightbulb(1);
lb2 = new Lightbulb(2);
lb3 = new Lightbulb(3);
lb4 = new Lightbulb(4);
lb5 = new Lightbulb(5);
lb6 = new Lightbulb(6);
lights->add(lb1);
lights->add(lb2);
lights->add(lb3);
lights->add(lb4);
lights->add(lb5);
lights->add(lb6);
} 

void loop(){ 
lights->off();
delay((2)*1000);
lights->on();
delay((2)*1000);
} 

